### ISSUE TITLE
Parallax styling

### ISSUE THREAD

**Issue by beamalsky** [22kaguirre/22kaguirre.github.io#6]
Hi Karen! I spent a little more time on that parallax example and wanted to share it. Here's what I've got:
<img width="1197" alt="screen shot 2018-12-12 at 4 21 57 pm" src="https://user-images.githubusercontent.com/1094243/49902624-12a9ce80-fe2a-11e8-8471-e58a4627b7da.png">

...and here's how to recreate it:

`in index.html`
```html
<div class="parallax-window" data-z-index="1" data-parallax="scroll" data-image-src="static/images/westside.jpg">
    <p class="sectionhead"><b>Live Healthy, West Side: <br />A West Side United Initiative</b></p>
</div>
```

in `custom.css`
```css
.container {
  max-width: 960px;
  margin: 0 auto;
  font-size: 24px;
  padding: 25px;
}

.parallax-window {
  color: white;
  text-shadow: 2px 2px rgba(0,0,0,0.7);
  padding: 100px 35px;
  background: transparent;
}

.sectionhead {
  z-index: 2;
  position: relative;
  font-size: 50px;
  text-align: center;
}
```

For this setup, you'll want one of these parallax images at the top of each section followed by a `<container></containter>` tag containing everything in the section.
